server:
  port: 8443
  ssl:
    key-store: file:///D:\Learning_projects\SPRING-IN-ACTION\taco-cloud\mykeys.jks
    key-password: ${KEYSTORE_PASSWORD}
    key-store-password: ${KEYSTORE_PASSWORD}

spring:
  application:
    name: taco-cloud

  # thymeleaf
  thymeleaf:
    cache: false

# БД
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  datasource:
    generate-unique-name: false
    name: tacocloud
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: email, public_profile
