spring:
  application:
    name: taco-cloud

  # thymeleaf
  thymeleaf:
    cache: false

# БД
  datasource:
    generate-unique-name: false
    name: tacocloud
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop  # Создаёт таблицы при старте, удаляет при завершении
    show-sql: true
    sql:
      init:
        mode: always  # Гарантирует выполнение import.sql
      defer-datasource-initialization: true  # Ждёт создания таблиц

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: email, public_profile
