spring:
  application:
    name: taco-cloud

  # thymeleaf
  thymeleaf:
    cache: false

# БД
  datasource:
    generate-unique-name: false
    name: tacocloud
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop  # Создаёт таблицы при старте, удаляет при завершении
    show-sql: true
    sql:
      init:
        mode: always  # Гарантирует выполнение import.sql
      defer-datasource-initialization: true  # Ждёт создания таблиц

  logging:
    level:
      org.springframework.jdbc.datasource.init: DEBUG
